export const ARENA_WIDTH = 960;
export const ARENA_HEIGHT = 640;
export const TANK_RADIUS = 20;
export const BULLET_RADIUS = 5;
export const MAX_BOUNCES = 4;
export const MAX_TICKS = 60 * 25;
export const SNAPSHOT_INTERVAL = 3;
export const TANK_MAX_HEALTH = 3;
export const BULLET_LIFETIME_TICKS = 60 * 8;
